x-common-config:
  &common-config
  restart: always

services:

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    <<: *common-config
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  astra:
    image: husarion/astra:humble
    <<: *common-config
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py

  image_compressor:
    image: husarion/image-transport:humble
    <<: *common-config
    command: >
      ros2 run image_transport republish raw ${CODEC:-theora}
        --ros-args
        --remap in:=/camera/color/image_raw
        --remap out/${CODEC:-theora}:=/camera/color/image_raw/${CODEC:-theora}
        
  dds-router:
    image: husarnet/dds-router:local-participant-whitelist
    <<: *common-config
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - DISCOVERY_SERVER_PORT=11888
      - WHITELIST_INTERFACES=172.22.0.1

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
