services:

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    # environment:
    #   - ROS_DOMAIN_ID=1
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    devices:
      - ${SERIAL_PORT:?err}
    # environment:
    #   - ROS_DOMAIN_ID=1
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  astra:
    image: husarion/astra:humble
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    # environment:
    #   - ROS_DOMAIN_ID=1
    command: ros2 launch astra_camera astra_mini.launch.py

  image_compressor:
    image: husarion/image-transport:humble
    # environment:
    #   - ROS_DOMAIN_ID=1
    command: >
      ros2 run image_transport republish raw ${CODEC:-theora}
        --ros-args
        --remap in:=/camera/color/image_raw
        --remap out/${CODEC:-theora}:=/camera/color/image_raw/${CODEC:-theora}
        
  dds-router:
    image: husarnet/dds-router:topic-filtering
    network_mode: host
    environment:
      # - ROS_DOMAIN_ID=1
      - DISCOVERY=SERVER
      - DS_HOSTNAME=rosbot2r
      - DS_SERVER_ID=4
      - DS_CLIENT_ID=9
    volumes:
      - ./filter.yaml:/filter.yaml
      - ./config.client.template.yaml:/config.client.template.yaml
      - ./config.server.template.yaml:/config.server.template.yaml
      - ./config.wan.template.yaml:/config.wan.template.yaml
      - ./entrypoint.sh:/entrypoint.sh
      - ./config_daemon.sh:/config_daemon.sh