x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  image_decompressor:
    image: husarion/image-transport:humble
    restart: always
    command: >
      ros2 run image_transport republish theora raw
      --ros-args
      --remap in/theora:=/oak/rgb/image_raw/theora
      --remap out:=/camera/my_image_raw

  # if you have NVDIA GPU and NVIDIA Container Toolkit, you can replace
  # "cpu-config" with "gpu-config"
  interface:
    image: husarion/image-tools:humble
    restart: always
    <<: *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run image_tools showimage --ros-args -p reliability:=best_effort --remap image:=/camera/my_image_raw

  ddsrouter:
    image: husarnet/dds-router:v2.0.0
    restart: always
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      ROS_DISCOVERY_SERVER: rosbot2r:11888
      ID: 1
      WHITELIST_INTERFACES: 172.22.0.1 127.0.0.1


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
