services:

  rviz:
    image: husarion/rviz2:iron-12.4.5-20231213
    network_mode: host
    ipc: host
    restart: unless-stopped
    # runtime: nvidia # uncomment if you want to use GPU for rendering
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1 # comment if you want to use CPU for rendering
      # - NVIDIA_VISIBLE_DEVICES=all # uncomment if you want to use GPU for rendering
      # - NVIDIA_DRIVER_CAPABILITIES=all # uncomment if you want to use GPU for rendering
      # envs for Husarnet setup
      - ROS_DISCOVERY_SERVER=${ROSBOT_HOSTNAME}:11811