services:

  foxglove:
    image: husarion/foxglove:humble-1.39.1-20230220
    ports:
      - 8080:8080
    volumes:
      - ./params/RosbotTeleop.json:/src/FoxgloveDefaultLayout.json
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230505-stable
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    devices:
      - ${SERIAL_PORT:?err}
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  astra:
    image: husarion/astra:humble-1.0.2-20230710-stable
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py

  image_compressor:
    image: husarion/image-transport:humble-4.2.0-20230216
    command: >
      ros2 run image_transport republish raw compressed
        --ros-args
        --remap in:=/camera/color/image_raw
        --remap out/compressed:=/camera/color/image_raw/compressed
