x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

services:

  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231211
    <<: *net-config
    devices:
      - ${SERIAL_PORT:?err}
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000

  astra:
    image: husarion/astra:humble-1.0.2-20231206-stable
    <<: *net-config
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py
