x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-cpu-config:
  &cpu-config
  env_file: .env.cpu

x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

x-ros-envs:
  &ros-envs
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
    - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-robot}
    - USER

services:

  ros2router:
    image: husarnet/ros2router:1.6.3
    <<: *common-config
    environment:
      - USER
      # ==========================
      # envs for Husarnet setup
      # ==========================
      - ROS_DISCOVERY_SERVER=${ROBOT_NAMESPACE}:11811
      - DISCOVERY_SERVER_ID=10 # need to be different as ros2router on ROSbot
      # ==========================
      # envs for LAN setup
      # ==========================
      # - ROS_LOCALHOST_ONLY=0
      # - HUSARNET_PARTICIPANT_ENABLED=false

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    <<: 
      - *common-config
      - *ros-envs
      - *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./params/default.rviz:/default.rviz
      - ./rviz.launch.py:/rviz.launch.py
    command: ros2 launch /rviz.launch.py

  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20240105
    <<: 
      - *common-config
      - *ros-envs
    devices:
      - /dev/input
    volumes:
      - ./params/joy2twist.yaml:/params.yaml
    command: >
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/params.yaml
        namespace:=${ROBOT_NAMESPACE}
