x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.6.3
    <<: *common-config
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - VIDEO_CODEC=ffmpeg # can be `ffmpeg`, `theora` or `compressed`
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-robot}
      - USER
      # ==========================
      # envs for Husarnet setup
      # ==========================
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
      # ==========================
      # envs for LAN setup
      # ==========================
      # - ROS_LOCALHOST_ONLY=0
      # - HUSARNET_PARTICIPANT_ENABLED=false

  rosbot:
    image: husarion/rosbot:humble-0.13.1-20240201
    <<:
      - *common-config
      - *dds-envs
    devices:
      - ${SERIAL_PORT:?err}
      # - /dev/bus/usb/ # FTDI
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-robot}
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT
        serial_baudrate:=576000

  astra:
    image: husarion/astra:humble-1.1.0-20240111
    <<:
      - *common-config
      - *dds-envs
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/husarion_utils/astra_params.yaml
    command: >
      ros2 launch /husarion_utils/astra.launch.py
        robot_namespace:=${ROBOT_NAMESPACE:-robot}
