x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: always

x-ros-envs:
  &ros-envs
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
    - ROBOT_NAMESPACE=$ROSBOT_HOSTNAME
    - USER

services:

  rosbot:
    image: husarion/rosbot:humble-shm-simple-test
    <<: 
      - *common-config
      - *ros-envs
    devices:
      - ${SERIAL_PORT:?err}
      # - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        namespace:=${ROSBOT_HOSTNAME:-robot}
        serial_baudrate:=576000
        
  astra:
    image: husarion/astra:humble-namespace
    <<: 
      - *common-config
      - *ros-envs
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/husarion_utils/astra_params.yaml
    command: >
      ros2 launch /husarion_utils/astra.launch.py
        robot_namespace:=${ROSBOT_HOSTNAME:-robot}
        device_namespace:=camera

  ros2router:
    image: husarnet/ros2router:filter-env
    <<: *common-config
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - ROSBOT_HOSTNAME=${ROSBOT_HOSTNAME:-robot}
    # # envs for LAN setup
    #   - ROS_LOCALHOST_ONLY=0
    #   - HUSARNET_PARTICIPANT_ENABLED=false
    #   - USER
    # envs for Husarnet setup
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
      - USER

