x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rviz:
    image: husarion/rviz2:iron-12.4.5-20231213
    <<: [ *net-config, *cpu-config ]
    # runtime: nvidia # uncomment if you want to use GPU for rendering
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
      # - ./fastdds.xml:/fastdds.xml
    # environment:
    #   - DISPLAY=${DISPLAY:?err}
      # - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
