x-net-config:
  &net-config
  network_mode: host
  ipc: host
  # pid: host
  env_file: net.env

services:

  microros:
    # image: husarion/micro-ros-agent:iron-3.1.3-20231122
    image: husarion/micro-ros-agent:humble-3.1.3-20231122
    <<: *net-config
    devices:
      - ${SERIAL_PORT:?err}
    volumes:
      - ./fastdds.xml:/fastdds.xml
    environment:
      # - RMW_FASTRTPS_USE_QOS_FROM_XML=1
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6

  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231211
    # image: husarion/rosbot:iron-0.11.0-20231211
    <<: *net-config
    command: ros2 launch rosbot_bringup bringup.launch.py
    # command: tail -f /dev/null
    volumes:
      - ./fastdds.xml:/fastdds.xml
    environment:
      # - RMW_FASTRTPS_USE_QOS_FROM_XML=1
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
    # devices:
    #   - ${SERIAL_PORT:?err}
    # command: >
    #   ros2 launch rosbot_bringup combined.launch.py 
    #     mecanum:=${MECANUM:-False}
    #     serial_port:=$SERIAL_PORT 
    #     serial_baudrate:=576000

  astra:
    image: husarion/astra:humble-1.0.2-20231206-stable
    <<: *net-config
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
      # - ./fastdds.xml:/fastdds.xml
    # environment:
    #   - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
    command: ros2 launch astra_camera astra_mini.launch.py

  # astra:
  #   image: husarion/orbbec-camera:humble-1.4.2-20231206-stable
  #   <<: *net-config
  #   devices:
  #     - /dev/bus/usb/
  #   volumes:
  #     - ./params/astra.yaml:/ros2_ws/install/orbbec_camera/share/orbbec_camera/params/astra_mini_params.yaml
  #   # command: ros2 launch astra_camera astra_mini.launch.py
  #   command: ros2 launch orbbec_camera dabai.launch.py