services:

  foxglove:
    image: husarion/foxglove:1.74.1
    ports:
      - 8080:8080
    volumes:
      - ./params/RosbotTeleop.json:/src/FoxgloveDefaultLayout.json
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  rosbridge:
    image: husarion/rosbridge-server:humble-1.3.1-20230831-stable
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml  

  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231211
    devices:
      - ${SERIAL_PORT:?err}
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000

  astra:
    image: husarion/astra:humble-1.0.2-20231206-stable
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py


