services:

  foxglove:
    image: husarion/foxglove:1.83.0
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./params/RosbotTeleopFull.json:/foxglove/default-layout.json
    environment:
      # - DS_TYPE=rosbridge-websocket
      # - DS_PORT=9090
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=foxglove-ds
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  # rosbridge-ds:
  #   image: husarion/rosbridge-server:humble-1.3.1-20230831-stable
  #   ports:
  #     - 9090:9090
  #   command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.3-20240108
    restart: unless-stopped
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,parameters,parametersSubscribe,services,connectionGraph,assets]

  rosbot:
    image: husarion/rosbot:humble-0.13.1-20240201
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT:?err}
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT
        serial_baudrate:=576000

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20240104
    restart: unless-stopped
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-256000}

  astra:
    image: husarion/astra:humble-1.1.0-20240104
    restart: unless-stopped
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/husarion_utils/astra_params.yaml
    command: ros2 launch /husarion_utils/astra.launch.py
