x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: always
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml

services:

  rosbot:
    image: husarion/rosbot:humble-0.11.0-20231211
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
      # - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000
        namespace:=${ROS_NAMESPACE}

  astra:
    image: husarion/astra:humble-1.0.2-20231206-stable
    <<: *common-config
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py
        
  ros2router:
    image: husarnet/ros2router:1.5.0
    network_mode: host
    ipc: host
    restart: always
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
    # # envs for LAN setup
    #   - ROS_LOCALHOST_ONLY=0
    #   - USE_HUSARNET=false
    # envs for Husarnet setup
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
      - ROS_NAMESPACE
