x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    restart: always
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    restart: always
    devices:
      - ${SERIAL_PORT:?err}
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  luxonis:
    image: husarion/depthai:humble-2.8.1
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./params/oak-1.yaml:/ros2_ws/install/depthai_ros_driver/share/depthai_ros_driver/config/camera.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    command: ros2 launch depthai_ros_driver camera.launch.py parent_frame:=oak-1-base-frame
        
  ddsrouter:
    image: husarnet/dds-router:v2.0.0
    restart: always
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      LISTENING_PORT: 11888
      ID: 0
      WHITELIST_INTERFACES: 172.22.0.1 # do demo Macka trzeba uruchomić bez tej linijki

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
