x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  image_decompressor:
    image: husarion/image-transport:humble
    restart: always
    command: >
      ros2 run image_transport republish ${CODEC:-theora} raw
      --ros-args
      --remap in/${CODEC:-theora}:=/camera/color/image_raw/${CODEC:-theora}
      --remap out:=/camera/my_image_raw

  # if you have NVDIA GPU and NVIDIA Container Toolkit, you can replace
  # "cpu-config" with "gpu-config"
  interface:
    image: husarion/image-tools:humble
    restart: always
    <<: *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run image_tools showimage --ros-args -p reliability:=best_effort --remap image:=/camera/my_image_raw

  ros2router:
    image: husarnet/ros2router:1.0.0
    restart: always
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      WHITELIST_INTERFACES: 172.22.0.1 127.0.0.1

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24

  # joy2twist:
  #   image: husarion/joy2twist:humble
  #   network_mode: host
  #   devices:
  #     - /dev/input
  #   volumes:
  #     - ./params/joy2twist.yaml:/params.yaml
  #   command: >
  #     ros2 launch joy2twist gamepad_controller.launch.py
  #       joy2twist_params_file:=/params.yaml