services:

  rosbot:
    image: husarion/rosbot:humble-0.6.1-20230712
    restart: always
    network_mode: bridge
    command: ros2 launch rosbot_bringup bringup.launch.py

  microros:
    image: husarion/micro-xrce-agent:v2.4.1
    restart: always
    network_mode: bridge
    devices:
      - ${SERIAL_PORT:?err}
    command: MicroXRCEAgent serial -D $SERIAL_PORT serial -b 576000

  astra:
    image: husarion/astra:humble
    restart: always
    network_mode: bridge
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py

  image_compressor:
    image: husarion/image-transport:humble
    restart: always
    network_mode: bridge
    command: >
      ros2 run image_transport republish raw ${CODEC:-theora}
        --ros-args
        --remap in:=/camera/color/image_raw
        --remap out/${CODEC:-theora}:=/camera/color/image_raw/${CODEC:-theora}
        
  ros2router:
    image: husarnet/ros2router:1.0.0
    restart: always
    network_mode: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      WHITELIST_INTERFACES: 172.17.0.1

