x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: always
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
    - USER

services:

  rosbot:
    image: husarion/rosbot:humble-shm-simple-test
    <<: *common-config
    devices:
      - ${SERIAL_PORT:?err}
      # - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000
# namespace:=${ROS_NAMESPACE}

  astra:
    image: husarion/astra:humble-namespace
    <<: *common-config
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/husarion_utils/astra_params.yaml
    # command: ros2 launch astra_camera astra_mini.launch.py
    command: tail -f /dev/null
    # command: ros2 launch /husarion_utils/astra.launch.py
        
  ros2router:
    image: husarnet/ros2router:husarnet-api-host
    network_mode: host
    ipc: host
    restart: always
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
    # # envs for LAN setup
    #   - ROS_LOCALHOST_ONLY=0
    #   - HUSARNET_PARTICIPANT_ENABLED=false
    #   - USER
    # envs for Husarnet setup
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
      - USER
# - ROS_NAMESPACE
